trigger:
  branches:
    include:
      - main
pool:agent_bikram
stages:
  - stage: infraStage
  displayname:"Infra_stage"
  jobs:
  -job:Terraformjob
  displayname:"terraform-infra"
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'bikram_serviceconnection'
      backendAzureRmStorageAccountName: 'bikram8thaug'
      backendAzureRmContainerName: 'bikramcontainers'
      backendAzureRmKey: 'terraform.tfstate'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      environmentServiceNameAzureRM: 'bikram_serviceconnection'
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      environmentServiceNameAzureRM: 'bikram_serviceconnection'
      
