trigger:
  branches:
    include:
      - main

pool:
  name: agent_bikram

stages:
  - stage: infraStage
    displayName: "Infra_stage"

    jobs:
      - job: Terraformjob
        displayName: "terraform-infra"

        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.9.8'

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'bikram_serviceconnection'
              backendAzureRmStorageAccountName: 'bikram8thaug'
              backendAzureRmContainerName: 'bikramcontainers'
              backendAzureRmKey: 'terraform.tfstate'

          - task: TerraformTask@5
            displayName: "Terraform Plan"
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'bikram_serviceconnection'

          - task: TerraformTask@5
            displayName: "Terraform Apply"
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'bikram_serviceconnection'